-- ============================================================================
-- Session 3 — CDC continuous-evaluation WRITE side.
-- Adds:
--   • enum EvalPhase  (REGULAR, AFTER_SUPPORT)
--   • enum ChangeKind (CREATE, UPDATE)
--   • table continuous_records         — per (student, outcome, session, phase)
--   • table continuous_record_history  — append-only audit log
--   • named CHECK constraint enforcing rating ∈ {1..4} at the DB level
--
-- SQL body below was generated by `prisma migrate diff
--   --from-schema-datasource prisma/schema.prisma
--   --to-schema-datamodel    prisma/schema.prisma
--   --script` (Prisma 6.19.3) and is therefore byte-for-byte the output
-- Prisma would have produced via `migrate dev` on a healthy shadow DB.
-- The CHECK constraint at the very bottom is the manual addition Prisma
-- cannot express in its DSL; it lives in the SAME migration file (per
-- the codebase's existing raw-SQL append pattern) so a single
-- `migrate deploy` lands the column AND the constraint atomically.
-- ============================================================================

-- CreateEnum
CREATE TYPE "EvalPhase" AS ENUM ('REGULAR', 'AFTER_SUPPORT');

-- CreateEnum
CREATE TYPE "ChangeKind" AS ENUM ('CREATE', 'UPDATE');

-- CreateTable
CREATE TABLE "continuous_records" (
    "id" UUID NOT NULL,
    "schoolId" UUID NOT NULL,
    "studentId" UUID NOT NULL,
    "outcomeId" TEXT NOT NULL,
    "sessionId" UUID NOT NULL,
    "phase" "EvalPhase" NOT NULL,
    "rating" INTEGER NOT NULL,
    "notes" TEXT,
    "createdById" UUID,
    "updatedById" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "continuous_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "continuous_record_history" (
    "id" UUID NOT NULL,
    "recordId" UUID NOT NULL,
    "changeKind" "ChangeKind" NOT NULL,
    "rating" INTEGER NOT NULL,
    "phase" "EvalPhase" NOT NULL,
    "notes" TEXT,
    "previousRating" INTEGER,
    "previousNotes" TEXT,
    "changedById" UUID,
    "changedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "continuous_record_history_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "continuous_records_schoolId_idx" ON "continuous_records"("schoolId");

-- CreateIndex
CREATE INDEX "continuous_records_sessionId_idx" ON "continuous_records"("sessionId");

-- CreateIndex
CREATE INDEX "continuous_records_studentId_sessionId_idx" ON "continuous_records"("studentId", "sessionId");

-- CreateIndex
CREATE UNIQUE INDEX "continuous_records_studentId_outcomeId_sessionId_phase_key" ON "continuous_records"("studentId", "outcomeId", "sessionId", "phase");

-- CreateIndex
CREATE INDEX "continuous_record_history_recordId_idx" ON "continuous_record_history"("recordId");

-- CreateIndex
CREATE INDEX "continuous_record_history_changedAt_idx" ON "continuous_record_history"("changedAt");

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_schoolId_fkey" FOREIGN KEY ("schoolId") REFERENCES "schools"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_outcomeId_fkey" FOREIGN KEY ("outcomeId") REFERENCES "learning_outcomes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "academic_sessions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_records" ADD CONSTRAINT "continuous_records_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_record_history" ADD CONSTRAINT "continuous_record_history_recordId_fkey" FOREIGN KEY ("recordId") REFERENCES "continuous_records"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "continuous_record_history" ADD CONSTRAINT "continuous_record_history_changedById_fkey" FOREIGN KEY ("changedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- DB CHECK constraint — rating range. Prisma's DSL cannot express CHECKs,
-- so it's appended here at the bottom of the same migration file (same
-- pattern as the IF-EXISTS pre-condition DROPs elsewhere in this tree).
-- Named so future schema reviews can grep for the invariant.
-- ============================================================================
ALTER TABLE "continuous_records"
  ADD CONSTRAINT "continuous_records_rating_range_check"
  CHECK ("rating" BETWEEN 1 AND 4);
